name: update-formula

on:
  repository_dispatch:
    types: [update-brew]

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.event.client_payload.tag }}

    steps:
      - uses: actions/checkout@v4

      # x86_64
      - name: Download x86_64 artifact
        run: |
          URL="https://github.com/taku-256/xgraft/releases/download/${TAG}/xgraft-${TAG}-x86_64-apple-darwin.tar.gz"
          curl -L "$URL" -o x86.tar.gz

      - name: SHA x86_64
        id: sha_x86
        run: |
          echo "sha=$(shasum -a 256 x86.tar.gz | awk '{print $1}')" >> "$GITHUB_OUTPUT"

      # ARM64
      - name: Download arm64 artifact
        run: |
          URL="https://github.com/taku-256/xgraft/releases/download/${TAG}/xgraft-${TAG}-aarch64-apple-darwin.tar.gz"
          curl -L "$URL" -o arm.tar.gz

      - name: SHA arm64
        id: sha_arm
        run: |
          echo "sha=$(shasum -a 256 arm.tar.gz | awk '{print $1}')" >> "$GITHUB_OUTPUT"

      # Formula生成
      - name: Write Formula
        run: |
          python3 scripts/write_formula.py \
            "${{ steps.sha_x86.outputs.sha }}" \
            "${{ steps.sha_arm.outputs.sha }}"

      # commit
      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Formula/xgraft.rb
          git commit -m "brew: update ${TAG}" || exit 0
          git push